module.exports = [
  { Name: "Darth Vader",
    Politician: "Yes",
    Moustache: "No",
    Mask: "Yes",
    Hair: "No",
    Nationality: "Tatooinian",
  },
  { Name: "Ming The Merciless",
    Politician: "Yes",
    Moustache: "Yes",
    Mask: "No",
    Hair: "Yes",
    Nationality: "Mongolian",
  },
  { Name: "Skeletor",
    Politician: "No",
    Moustache: "No",
    Mask: "No",
    Hair: "No",
    Nationality: "Eternian",
  },
  { Name: "Hitler",
    Politician: "Yes",
    Moustache: "Yes",
    Mask: "No",
    Hair: "Yes",
    Nationality: "German",
  },
  { Name: "Stalin",
    Politician: "Yes",
    Moustache: "Yes",
    Mask: "No",
    Hair: "Yes",
    Nationality: "Russian",
  },
  { Name: "Trump",
    Politician: "Yes",
    Moustache: "No",
    Mask: "No",
    Hair: "Yes",
    Nationality: "American",
  },
  { Name: "Joffrey",
    Politician: "Yes",
    Moustache: "No",
    Mask: "No",
    Hair: "Yes",
    Nationality: "Westerosi",
  },
  { Name: "Dr Doom",
    Politician: "Yes",
    Moustache: "No",
    Mask: "Yes",
    Hair: "No",
    Nationality: "Latverian",
  },
  { Name: "Justin Bieber",
    Politician: "No",
    Moustache: "No",
    Mask: "No",
    Hair: "Yes",
    Nationality: "Canada",
  },
  { Name: "Mumm-Ra",
    Politician: "No",
    Moustache: "No",
    Mask: "No",
    Hair: "No",
    Nationality: "Thunderian",
  }
]